kind: Deployment
apiVersion: apps/v1
metadata:
  name: idealimport-svc
  namespace: ideal-import
  labels:
    app: idealimport-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idealimport-svc
  template:
    metadata:
      namespace: ideal-import
      creationTimestamp: null
      labels:
        app: idealimport-svc
    spec:
      containers:
        - name: idealimport-svc
          image: 'nasruddinkhan/idealimport-svc:2.0.7'
          envFrom:
            - configMapRef:
                name: application-config
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600