apiVersion: v1
kind: Application
metadata:
  name: ideal-import
  namespace: argocd 
spec:
  destination:
    namespace: ideal-import
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ideal-import-app/ideal-import-ui
    repoURL: https://github.com/Nasruddinkhan/argo-cd
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

    