apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ideal-import
  namespace: argocd 
spec:
  destination:
    namespace: ideal-import
    server: https://kubernetes.default.svc
  project: default
  source:
    - repoURL: https://github.com/Nasruddinkhan/argo-cd
      path: ideal-import-app/ideal-import-ui
      targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

    