apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ideal-import
  namespace: argocd 
spec:
  destination:
    namespace: ideal-import-app
    server: https://kubernetes.default.svc
  project: ideal-import-app
  source:
    path: ideal-import-app/mysql
    repoURL: https://github.com/Nasruddinkhan/argo-cd.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
