kind: Deployment
apiVersion: apps/v1
metadata:
  name: svc-db
  namespace: ideal-import
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: svc-db
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'true'
      labels:
        deployment: svc-db
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: svc-db-pvc
      containers:
        - name: mysql
          image: >-
            mysql@sha256:c2e99ad580f5f03f4e0f09f22169d90c561da383781531fe712f6eb0e494d332
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              memory: 1Gi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - name: data-volume
              mountPath: /var/lib/mysql
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: { }
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600