kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: svc-db-pvc
  namespace: ideal-import
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem