kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: kube-logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem