kind: Deployment
apiVersion: apps/v1
metadata:
  name: ideal-import-app
  namespace: nasruddinkhan786-dev
  labels:
    app: ideal-import-app
    group: cnd.com.idealimport
    provider: jkube
    version: 0.0.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ideal-import-app
      group: cnd.com.idealimport
      provider: jkube
  template:
    metadata:
      namespace: nasruddinkhan786-dev
      creationTimestamp: null
      labels:
        app: ideal-import-app
        group: cnd.com.idealimport
        provider: jkube
        version: 0.0.3
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: nasruddinkhan-ideal-import-app
          securityContext:
            privileged: false
          ports:
            - name: us-srv
              containerPort: 8083
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: application-config
          image: 'nasruddinkhan/ideal-import-app:0.0.8'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
