kind: Service
apiVersion: v1
metadata:
  name: ideal-import-app
  namespace: ideal-import
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30134
  type: NodePort
  selector:
    app: ideal-import-app

