kind: Service
apiVersion: v1
metadata:
  name: ideal-import-app
  namespace: ideal-import
spec:
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  #type: NodePort
  #type: LoadBalancer
  #type: ClusterIP
  selector:
    app: ideal-import-app

